loadFinishSound = "minecraft:ui.toast.challenge_complete"
minMemory = 6.0
errorTitle = "Error: Not enough Java memory!"
errorMinMemory = "Please allocate at least {minMemory} GB of Java memory to your Minecraft instance! If you want to use shaders AND Distant Horizons, use 8GB! (8192)"
errorCurrentMemory = "You have currently {currentMemory} GB allocated."
memoryInfoLink = "https://github.com/vaporvee/LoadSupport/wiki/How-to-allocate-more-memory-to-your-Minecraft-instance"
