# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fast"
# The chunk rebuild scheduler mode (immediate, culling).
chunk_rebuild_scheduler = "culling"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enables dynamic lighting of beacon or end gateway beams.
	beam = true
	# Enables dynamic lighting of firefly particles from Firefly Bushes.
	firefly = true
	# Enables dynamic lighting for entities that have the Glowing effect.
	glowing_effect = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Enables dynamic lighting of the Warden's sonic boom attack particles.
	sonic_boom = false
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "off"
	# Enables dynamic lighting of Guardian's lasers. This also can be toggled off by disabling Guardian dynamic lighting.
	guardian_laser = false

			[light_sources.settings.entities.minecraft]
				zombie_horse = true
				axolotl = true
				egg = true
				zoglin = true
				spawner_minecart = true
				allay = true
				llama = true
				mule = true
				bat = true
				husk = true
				camel = true
				experience_bottle = true
				rabbit = true
				firework_rocket = true
				silverfish = true
				giant = true
				drowned = true
				item = true
				goat = true
				horse = true
				vindicator = true
				minecart = true
				spectral_arrow = true
				llama_spit = true
				mooshroom = true
				glow_item_frame = false
				tnt = true
				snowball = true
				parrot = true
				creeper = true
				lightning_bolt = true
				tadpole = true
				ravager = true
				evoker_fangs = true
				chest_minecart = true
				tropical_fish = true
				slime = true
				pillager = true
				area_effect_cloud = true
				blaze = true
				piglin = true
				end_crystal = true
				endermite = true
				ender_pearl = true
				zombie = true
				item_display = true
				breeze_wind_charge = true
				guardian = true
				fireball = true
				illusioner = true
				eye_of_ender = true
				wither_skull = true
				wolf = true
				block_display = true
				tnt_minecart = true
				zombie_villager = true
				elder_guardian = true
				chest_boat = true
				boat = true
				small_fireball = true
				strider = true
				cave_spider = true
				cod = true
				snow_golem = true
				witch = true
				spider = true
				command_block_minecart = true
				panda = true
				bee = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				frog = true
				hoglin = true
				armadillo = true
				armor_stand = true
				experience_orb = true
				dolphin = true
				stray = true
				shulker = true
				turtle = true
				salmon = true
				vex = true
				wandering_trader = true
				wither_skeleton = true
				piglin_brute = true
				breeze = true
				ocelot = true
				furnace_minecart = true
				item_frame = true
				phantom = true
				ender_dragon = true
				leash_knot = true
				evoker = true
				marker = true
				glow_squid = true
				warden = true
				squid = true
				shulker_bullet = true
				enderman = true
				dragon_fireball = true
				chicken = true
				sniffer = true
				trader_llama = true
				donkey = true
				bogged = true
				fox = true
				iron_golem = true
				zombified_piglin = true
				cat = true
				wind_charge = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				trident = true
				villager = true
				ominous_item_spawner = true
				skeleton_horse = true
				fishing_bobber = true
				text_display = true
				polar_bear = true
				hopper_minecart = true
				falling_block = true
				painting = true
				interaction = true
				wither = true

			[light_sources.settings.entities.farmersdelight]
				rotten_tomato = true

			[light_sources.settings.entities.handcrafted]
				seat = true
				fancy_painting = true

			[light_sources.settings.entities.legendarymonuments]
				distortion_portal = true

			[light_sources.settings.entities.create_things_and_misc]
				blaze_ballon_fire_projectile = true
				spout_gun_slime_projectile = true
				spout_gun_lava_projectile = true
				stoup_gun_water_projectile = true
				neon_tube_projectile = true
				sprinkler_head = true
				spout_gun_chocolate_projectile = true
				sprinkler_radius = true
				balloon_blaze = true
				spout_gun_honey_projectile = true

			[light_sources.settings.entities.fetzisasiandeco]
				seat = true
				koi = true
				fixed_seat = true

			[light_sources.settings.entities.cobbleloots]
				loot_ball = true

			[light_sources.settings.entities.cobblefurnies]
				seat = true

			[light_sources.settings.entities.amendments]
				medium_dragon_fireball = true
				falling_lantern = true
				medium_fireball = true

			[light_sources.settings.entities.another_furniture]
				seat = true

			[light_sources.settings.entities.cluttered]
				chair_entity = true

			[light_sources.settings.entities.rctmod]
				trainer_association = true
				trainer = true

			[light_sources.settings.entities.biomeswevegone]
				pumpkin_warden = true
				oddion = true
				man_o_war = true
				chest_boat = true
				wreath = true
				boat = true

			[light_sources.settings.entities.pokebike]
				yellow_bike = true
				green_bike = true
				red_bike = true
				blue_bike = true

			[light_sources.settings.entities.splash_milk]
				milk_bottle = true
				milk_area_effect_cloud = true

			[light_sources.settings.entities.cobblemon_secret_base_trainer]
				battle_clone = true

			[light_sources.settings.entities.create]
				carriage_contraption = true
				seat = true
				stationary_contraption = true
				package = true
				contraption = true
				gantry_contraption = true
				super_glue = true
				crafting_blueprint = true
				potato_projectile = true

			[light_sources.settings.entities.mynethersdelight]
				strider_rock = true

			[light_sources.settings.entities.frightsdelight]
				bone_shard = true

			[light_sources.settings.entities.expandeddelight]
				cinnamon_boat = true
				cinnamon_chest_boat = true

			[light_sources.settings.entities.simplehats]
				hatdisplay = true

			[light_sources.settings.entities.cobblemon]
				empty_pokeball = true
				npc = true
				pokemon = true
				generic_bedrock = true
				chest_boat = true
				poke_bobber = true
				boat = true

			[light_sources.settings.entities.immersive_paintings]
				glow_graffiti = true
				painting = true
				graffiti = true
				glow_painting = true

			[light_sources.settings.entities.xercapaint]
				canvas = true
				easel = true

			[light_sources.settings.entities.fightorflight]
				bullet_projectile = true
				tornado = true
				floating_spike_projectile = true
				magic_effect = true
				tracing_bullet = true
				whirlpool = true
				arrow_projectile = true
				spike_projectile = true
				sticky_web = true

			[light_sources.settings.entities.farmingforblockheads]
				merchant = true

			[light_sources.settings.entities.sophisticatedbackpacks]
				everlasting_backpack_item = true

			[light_sources.settings.entities.lootr]
				lootr_minecart = true
				item_frame = true

			[light_sources.settings.entities.mcwfurnitures]
				chair = true
				couch = true

			[light_sources.settings.entities.blueprint]
				falling_block = true
				chest_boat = true
				boat = true

			[light_sources.settings.entities.aquaculture]
				tuna = true
				birch_fish_mount = true
				jellyfish = true
				bluegill = true
				muskellunge = true
				water_arrow = true
				brown_shrooma = true
				catfish = true
				tambaqui = true
				pacific_halibut = true
				boulti = true
				rainbow_trout = true
				starshell_turtle = true
				gar = true
				oak_fish_mount = true
				acacia_fish_mount = true
				perch = true
				capitaine = true
				arrau_turtle = true
				atlantic_halibut = true
				dark_oak_fish_mount = true
				piranha = true
				blackfish = true
				jungle_fish_mount = true
				red_grouper = true
				spruce_fish_mount = true
				arapaima = true
				box_turtle = true
				atlantic_herring = true
				bayad = true
				pollock = true
				carp = true
				spectral_water_arrow = true
				red_shrooma = true
				atlantic_cod = true
				brown_trout = true
				pink_salmon = true
				synodontis = true
				smallmouth_bass = true
				bobber = true
				minnow = true

			[light_sources.settings.entities.fireworkcapsules]
				capsule_entity = true

			[light_sources.settings.entities.crabbersdelight]
				mod_chest_boat = true
				mod_boat = true
				crab = true

			[light_sources.settings.entities.supplementaries]
				dispenser_minecart = true
				slingshot_projectile = true
				brick_projectile = true
				plunderer = true
				falling_sack = true
				pearl_marker = true
				hat_stand = true
				bomb = true
				falling_ash = true
				cannonball = true
				falling_urn = true
				red_merchant = true
				cannon_boat = true
				rope_arrow = true
				slimeball_projectile = true

			[light_sources.settings.entities.cobbledollars]
				cobble_merchant = true

			[light_sources.settings.entities.pokeblocks]
				sittable = true

[debug]
	active_dynamic_lighting_cells = false
	display_dynamic_lighting_chunk_rebuild = false
	display_behavior_bounding_box = false

[adaptive_ticking]
	# Reduces how often sources behind the camera get ticked.
	background_sleep = true
	# How far away (in chunks) until light sources get ticked less often.
	slow = 5
	# How far away (in chunks) until light sources get ticked even less often.
	slower = 8
